name: Build in Docker and Save Log Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Возможность запуска вручную из интерфейса

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get -y install docker.io

      - name: Build Docker image
        run: |
          docker build -t lab3-4-builder .

      - name: Run container to build project
        run: |
          docker run --rm -v $(pwd)/logs:/logs lab3-4-builder

      - name: Check log file
        run: |
          cat logs/build.log || echo "Log file not found"

      - name: Upload log as artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-log
          path: logs/build.log
